/**
 * Employee Protal API
 * Manage the Employees of The Company
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelError { 
    code?: number;
    message?: string;
    fields?: string;
}
